keys:
  - &admin age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # Mainteners
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  # Contributers
  - &student_1 age1le65saguzfnrkm0t7ms07cxa36r4m65q8356p3u06n2ycsnwdg2qssad2p

creation_rules:
  # Rules for production secrets
  - path_regex: secrets/project-secrets.production.env
    key_groups:
      - age:
          - *admin
          - *larsg
  # Rules for development secrets
  - path_regex: secrets/project-secrets.development.env
    key_groups:
      - age:
          - *admin
          - *larsg
          - *student_1
